// Generated by CoffeeScript 1.4.0
(function() {
  var depthFirst, extend, forceCallback, forceCallbackWrap, helpers, parallelBucket, _,
    __slice = [].slice;

  _ = require('underscore');

  helpers = require('./index');

  exports.forceCallback = forceCallback = function() {
    var args, callback, f, ret, returned, _i;
    f = arguments[0], args = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), callback = arguments[_i++];
    returned = false;
    try {
      ret = f.apply(this, args.concat(function(err, data) {
        if (returned) {
          throw "got return value but also callback was called";
        }
        return callback(err, data);
      }));
    } catch (error) {
      callback(error, void 0);
    }
    if (ret !== void 0) {
      returned = true;
      return callback(void 0, ret);
    }
  };

  exports.forceCallbackWrap = forceCallbackWrap = function() {
    var args, f;
    f = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return function(callback) {
      return forceCallback.apply(this, [].concat(f, args, callback));
    };
  };

  exports.parallelBucket = parallelBucket = function() {
    this.n = 0;
    this._done = true;
    this.subs = [];
    this.data = {};
    this.error = void 0;
    return this;
  };

  parallelBucket.prototype.cb = function(name) {
    var _this = this;
    this.n++;
    this._done = false;
    if (!name) {
      name = this.n;
    }
    return function(err, data) {
      if (err) {
        if (!_this.error) {
          _this.error = {};
        }
        _this.error[name] = err;
      }
      _this.data[name] = data;
      --_this.n || (_this._done = true && _.map(_this.subs, function(sub) {
        return sub(_this.error, _this.data);
      }));
      return void 0;
    };
  };

  parallelBucket.prototype.done = function(callback) {
    if (this._done) {
      return callback(this.error, this.data);
    } else {
      return this.subs.push(callback);
    }
  };

  depthFirst = function(target, changecallback, clone, callback) {
    var bucket, key, response;
    if (target.constructor === Object || target.constructor === Array) {
      if (clone) {
        target = _.clone(target);
      }
      bucket = new parallelBucket();
      for (key in target) {
        this.depthfirst(target[key], changecallback, clone, function(data) {
          return target[key] = data;
        });
      }
      return target;
    } else if (response = callback(target)) {
      return response;
    } else {
      return target;
    }
  };

  exports.random = function(stuff) {
    return stuff[Math.floor(Math.random() * stuff.length)];
  };

  exports.randompop = function(stuff) {
    return stuff.splice(Math.floor(Math.random() * stuff.length), 1)[0];
  };

  exports.remove = function(stuff, element) {
    var i;
    i = stuff.indexOf(element);
    if (i !== -1) {
      stuff.splice(i, 1);
    }
    return stuff;
  };

  exports.shuffle = function(stuff) {
    var _results;
    stuff = _.clone(stuff);
    _results = [];
    while (stuff.length) {
      _results.push(exports.randompop(stuff));
    }
    return _results;
  };

  exports.commenterr = function(err, comment) {
    if (err) {
      return comment + ": " + err;
    } else {
      return void 0;
    }
  };

  exports.extend = extend = function() {
    var destination, targets;
    destination = arguments[0], targets = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _.map(targets, function(target) {
      return _.map(target, function(value, key) {
        var _ref;
        if (((_ref = destination[key]) != null ? _ref.constructor : void 0) === Object) {
          return destination[key] = extend(destination[key], value);
        } else {
          return destination[key] = value;
        }
      });
    });
    return destination;
  };

}).call(this);
