// Generated by CoffeeScript 1.8.0
(function() {
  var fs;

  fs = require('fs');

  exports.echo = function(file, data) {
    return fs.appendFile(file, String(data) + "\n");
  };

  exports.clearEcho = function(file, data) {
    return fs.writeFileSync(file, data);
  };

  exports.wrapEcho = function(file) {
    return function(data) {
      return exports.echo(file, data);
    };
  };

  exports.wrapClearEcho = function(file) {
    return function(data) {
      return exports.clearEcho(file, data);
    };
  };

}).call(this);
