// Generated by LiveScript 1.4.0
(function(){
  var _, h, p;
  _ = require('underscore');
  h = require('./index');
  p = require('bluebird');
  exports.retry = function(o, f){
    var this$ = this;
    return new p(function(resolve, reject){
      var dO, tryAgain;
      dO = {
        times: 10,
        delay: 100,
        delayf: void 8
      };
      if (o.constructor === Function) {
        f = o;
        o = {};
      }
      o = _.extend(dO, o);
      tryAgain = function(){
        return f().then(function(it){
          return resolve(it);
        })['catch'](function(it){
          o.times -= 1;
          if (o.times) {
            h.wait(o.delay, tryAgain);
            if (o.delayf != null) {
              return o.delay = o.delayf(o.delay);
            }
          } else {
            return reject(it);
          }
        });
      };
      return tryAgain();
    });
  };
  exports.queue = function(o){
    var dO, queue, activeJobs, work, push;
    dO = {
      size: 1
    };
    o = _.extend(dO, o);
    queue = [];
    activeJobs = 0;
    work = function(){
      var job, this$ = this;
      if (activeJobs === o.size) {
        return;
      }
      if (!queue.length) {
        return;
      }
      job = _.first(this.queue);
      return job()['finally'](function(){
        queue.shift();
        activeJobs = activeJobs - 1;
        return work();
      });
    };
    return push = function(job){
      queue.push(job);
      return work();
    };
  };
}).call(this);
