// Generated by CoffeeScript 1.9.1
(function() {
  var _,
    slice = [].slice;

  _ = require('underscore');

  exports.wrap = {
    once: function(f) {
      var gotData, options, ret;
      options = {
        state: 0,
        data: void 0,
        callbacks: []
      };
      gotData = function() {
        var data;
        data = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        options.data = data;
        options.state = 2;
        return _.each(options.callbacks, function(callback) {
          return callback.apply(this, options.data);
        });
      };
      ret = function(callback) {
        if (options.state === 2) {
          _.defer(function() {
            return callback.apply(this, options.data);
          });
        }
        options.callbacks.push(callback);
        if (options.state === 0) {
          options.state = 1;
          return f(gotData);
        }
      };
      return ret;
    }
  };

}).call(this);
